spring:
  application:
    name: jpyxie-spring-boot-graalpy-demo
  python:
    environment:
      global-python-executable: graalpy
      create-on-start: true
      remove-on-close: true
    executor:
      graalpy:
        additional-options:
          engine:
            WarnInterpreterOnly: false
          python:
            ForceImportSite: true
logging:
  level:
    io:
      jpyxie:
        python: DEBUG