spring:
  application:
    name: jpyxie-spring-boot-graalpy-demo
  python:
    environment:
      global-python-executable: graalpy
      create-on-start: true
      remove-on-close: true
    library:
      enabled: true
      installed:
        - name: numpy
        - name: pandas
        - name: matplotlib
        - name: scipy
      uninstalled:
        - name: numpy
        - name: pandas
        - name: matplotlib
        - name: scipy
    executor:
      graalpy:
        additional-options:
          engine:
            WarnInterpreterOnly: false
          python:
            ForceImportSite: true
logging:
  level:
    io:
      jpyxie:
        python: DEBUG