spring:
  application:
    name: jpyxie-spring-boot-graalpy-demo
  python:
    pip:
      library:
        enabled: true
        installed:
          - name: numpy
          - name: pandas
          - name: matplotlib
          - name: scipy
        uninstalled:
          - name: numpy
          - name: pandas
          - name: matplotlib
          - name: scipy
      timeout: 5m
    executor:
      graalpy:
        additional-options:
          engine:
            WarnInterpreterOnly: false
logging:
  level:
    io:
      jpyxie:
        python: DEBUG