# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'python.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpython.proto\"7\n\x11GrpcPythonRequest\x12\x0e\n\x06script\x18\x01 \x01(\t\x12\x12\n\nfieldNames\x18\x02 \x03(\t\"t\n\x12GrpcPythonResponse\x12/\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1f.GrpcPythonResponse.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x14GrpcPythonPipRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0blibraryName\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\"+\n\x15GrpcPythonPipResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x32\x86\x01\n\x11PythonGrpcService\x12\x35\n\x08SendCode\x12\x12.GrpcPythonRequest\x1a\x13.GrpcPythonResponse\"\x00\x12:\n\x07SendPip\x12\x15.GrpcPythonPipRequest\x1a\x16.GrpcPythonPipResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCPYTHONRESPONSE_FIELDSENTRY']._loaded_options = None
  _globals['_GRPCPYTHONRESPONSE_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_GRPCPYTHONREQUEST']._serialized_start=16
  _globals['_GRPCPYTHONREQUEST']._serialized_end=71
  _globals['_GRPCPYTHONRESPONSE']._serialized_start=73
  _globals['_GRPCPYTHONRESPONSE']._serialized_end=189
  _globals['_GRPCPYTHONRESPONSE_FIELDSENTRY']._serialized_start=144
  _globals['_GRPCPYTHONRESPONSE_FIELDSENTRY']._serialized_end=189
  _globals['_GRPCPYTHONPIPREQUEST']._serialized_start=191
  _globals['_GRPCPYTHONPIPREQUEST']._serialized_end=265
  _globals['_GRPCPYTHONPIPRESPONSE']._serialized_start=267
  _globals['_GRPCPYTHONPIPRESPONSE']._serialized_end=310
  _globals['_PYTHONGRPCSERVICE']._serialized_start=313
  _globals['_PYTHONGRPCSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
