spring:
  application:
    name: jpyxie-spring-boot-graalpy-demo
  python:
    environment:
      global-python-executable: python
      create-on-start: true
      remove-on-close: true
    library:
      enabled: true
      installed:
        - name: jep
          options:
            - --no-cache-dir
      uninstalled:
        - name: jep
logging:
  level:
    io:
      jpyxie:
        python: DEBUG