spring:
  application:
    name: jpyxie-spring-boot-jep-demo
  profiles:
    active: dev
  python:
    jep:
      python-library-path: ${PYTHON_LIBRARY_PATH}\python314.dll
      jep-library-path: ${JEP_LIBRARY_PATH}\jep.dll
    environment:
      global-python-executable: python
      create-on-start: true
      remove-on-close: true
logging:
  level:
    io:
      jpyxie:
        python: DEBUG