spring:
  application:
    name: jpyxie-spring-boot-process-demo
  python:
    environment:
      create-on-start: true
      remove-on-close: true
logging:
  level:
    io:
      jpyxie:
        python: DEBUG